app/src/app.js, app/src/templates/index.jadehtml, app/src/templates/lineInput.jade, app/src/util.js, app/src/views/AnalysisManagementView.js, app/src/views/AnalysisSetupView.js, app/src/views/DatasetManagementView.js, app/src/views/VisualizationManagementView.js
=> Adding ability to save preset visualizations

app/src/views/AnalysisManagementView.js, app/src/workflow.js
With this commit, you will no longer be able to modify a workflow unless you've enabled write access.
=> Enable read-only view of workflow diagrams

app/src/app.js, app/src/workflow.js
Move the delete step icon to the upper right, and have it only appear when the user mouses over the step.
@jeffbaumes PTAL.
=> Nicer workflow delete button

lib/js/d3.scatterplotmatrix.js
=> Added "Reset" button to Scatterplot Matrix

app/src/views/AnalysisSetupView.js
There were changes to both the REST API and the task specification
=> Work with the new romanesco API

app/src/stylesheets/index.styl, app/src/templates/index.jadehtml, app/src/util.js, app/src/views/AnalysisManagementView.js, app/src/views/AnalysisSetupView.js, app/src/workflow.js, test/lib/jasmine-1.3.1/ConsoleReporter.js
report success or error (with details) using our new alert system
=> provide feedback to user when "save analysis" is clicked

app/src/views/AnalysisManagementView.js, test/spec/appSpec.js
Confirm with the user when they're about to navigate away from unsaved changes to an analysis.
=> warn before abandoning unsaved changes

.gitignore, app/src/views/InputsView.js
Present an error message to the user when they attempt to setup an analysis or workflow & one of the inputs cannot be resolved.
=> Notify user when a bad input is detected

app/src/util.js, app/src/views/DatasetManagementView.js
Note that this branch depends on a very recent version of Girder.
=> Improve user feedback when datasets are loaded, saved, or deleted

app/src/views/VariableEditView.js
=> fix editing & displaying of default enum values

app/src/plugins/table.js, app/src/util.js, app/src/views/VisualizationManagementView.js
=> fix table editing capability

app/src/app.js
This depends on a forthcoming branch in girder/girder
=> Use core collection creation policies

app/src/app.js, app/src/util.js
@jeffbaumes 
Depends on #165 
Displays a warning that will persist until it can connect to a romanesco worker. It pops up after it's taken > 3 seconds to respond, this is somewhat arbitrary and open to suggestions.
=> Notify when a worker is taking too long to respond

devops/ansible/load-analyses.py
To test this out:
* vagrant ssh
* git clone https://github.com/lukejharmon/arborCollections
* cd /vagrant/devops/ansible
* python load-analyses.py ~/arborCollections
=> New script to batch load analyses

app/src/views/InputsView.js
Otherwise you have a mode equal to `HTTP` with a bad URL.
=> Only add Girder info if data is saved to Girder collection

app/src/util.js
Fixes #179
@jeffbaumes Mind taking a look?
=> Stop returning in-memory formats for download prompt

Gruntfile.js
Fixes #192 
@jeffbaumes @curtislisle
=> Run the static extras grunt task by default

web_external/js/util.js
=> Perform case-insensitive search for extensions

.travis.yml
This was required to get travis to start passing again.
=> Update travis to use newer version of node

devops/atmosphere/post-scripts.d/provision.sh
@curtislisle 
I think I'll have to create a new Arbor image once this goes in, in the mean time I've contacted support to see if there's a way I can update the existing image.
=> Brand as Arbor for Atmosphere

devops/easymode-setup.py
@curtislisle Take a look at this, it should address the issues you raised in #207.
The port was changed to 8080 to match vagrant, but you can also just specify a port with `-p` now if it happens to be running somewhere else.
=> Fix easymode script
